# Generated by Django 5.2.8 on 2025-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needy_status', models.CharField(choices=[('ORPHAN', 'Orphan'), ('SINGLE-PARENT', 'Single Parent'), ('LOW_INCOME', 'Low Income Family')], max_length=20)),
                ('institution_name', models.CharField(blank=True, choices=[('PRIMARY', 'Primary '), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], max_length=20, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='beneficiary_documents/')),
                ('age', models.PositiveBigIntegerField(default=18)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='other', max_length=10)),
                ('education_level', models.CharField(choices=[('PRIMARY', 'Primary '), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], default='secondary', max_length=20)),
                ('academic_performance', models.CharField(choices=[('EXCELLENT', 'Excellent (80-100%)'), ('GOOD', 'Good (60-79%)'), ('AVERAGE', 'Average (40-59%)'), ('BELOW_AVERAGE', 'Below Average (20-39%)'), ('POOR', 'Poor (0-19%)')], default='average', max_length=20)),
                ('application_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
