# Generated by Django 5.1.3 on 2025-02-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needy_status', models.CharField(choices=[('ORPHAN', 'Orphan'), ('SINGLE-PARENT', 'Single Parent'), ('LOW_INCOME', 'Low Income Family')], max_length=20)),
                ('institution_name', models.CharField(blank=True, choices=[('PRIMARY', 'Primary '), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], max_length=20, null=True)),
                ('academic_performance', models.CharField(blank=True, max_length=255, null=True)),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='beneficiary_documents/')),
                ('application_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
