# Generated by Django 5.1.3 on 2025-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='age',
            field=models.PositiveBigIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='academic_performance',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent (80-100%)'), ('GOOD', 'Good (60-79%)'), ('AVERAGE', 'Average (40-59%)'), ('BELOW_AVERAGE', 'Below Average (20-39%)'), ('POOR', 'Poor (0-19%)')], default='average', max_length=20),
        ),
    ]
