# Generated by Django 5.2.3 on 2025-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_age_beneficiary_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='education_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary '), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], default='secondary', max_length=20),
        ),
    ]
