# Generated by Django 5.2.8 on 2025-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('MONEY', 'Money'), ('STATIONERY', 'Stationary'), ('FOOD', 'Food'), ('FURNITURE', 'Furniture')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('gps_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
