# Generated by Django 5.2.3 on 2025-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_amount_alter_donation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='material_type',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('MONEY', 'Money'), ('STATIONERY', 'Stationary'), ('FOOD', 'Food'), ('FURNITURE', 'Furniture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash')], max_length=50, null=True),
        ),
    ]
